//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ТРИЗБД_4445
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TravelAgency11Entities : DbContext
    {
        private static TravelAgency11Entities _context;
        public TravelAgency11Entities()
            : base("name=TravelAgency11Entities")
        {
        }

        public static TravelAgency11Entities GetContext()
        {
            if (_context == null)
                _context = new TravelAgency11Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Booking> Booking { get; set; }
        public virtual DbSet<Client> Client { get; set; }
        public virtual DbSet<Guide> Guide { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
